name: 'tmate-ubuntu'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/50 * * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose tmate or ngrok mode'
        required: false
        default: 'tmate'

jobs:
  ssh-debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug input
        run: |
          echo "Input mode: ${{ github.event.inputs.mode }}"

      - name: Verify script exists
        run: |
          MODE="${{ github.event.inputs.mode }}"
          if [ -z "$MODE" ]; then
            echo "Error: MODE is not set."
            exit 1
          fi
          SCRIPT_PATH="./${MODE}2actions.sh"
          if [ ! -f "$SCRIPT_PATH" ]; then
            echo "Error: $SCRIPT_PATH does not exist."
            exit 1
          fi

      - name: Add execute permission
        run: |
          MODE="${{ github.event.inputs.mode }}"
          chmod +x ./${MODE}2actions.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate ngrok

      - name: Debug and run script
        run: |
          set -e
          set -x
          MODE="${{ github.event.inputs.mode }}"
          bash ./${MODE}2actions.sh
        shell: bash

      - name: Sleep
        run: sleep 1h
