name: 'tmate-ubuntu'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/50 * * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose tmate or ngrok mode'
        required: false
        default: 'tmate'

jobs:
  ssh-debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add execute permission
        run: chmod +x ./${{ github.event.inputs.mode }}2actions.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate ngrok

      - name: Choose mode tmate (ubuntu)
        run: |
          MODE=${{ github.event.inputs.mode }}
          bash ./${MODE}2actions.sh
        shell: bash

      - name: Sleep
        run: sleep 1h
