name: 'tmate-ubuntu'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/50 * * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose tmate or ngrok mode'
        required: false
        default: 'tmate'

jobs:
  ssh-debug:
    runs-on: ubuntu-22.04  # 明确指定运行环境，避免未来更新影响
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Choose mode tmate (ubuntu)
        run: |
          MODE=${{ github.event.inputs.mode }}
          bash ./${MODE}2actions.sh
        shell: bash
        
      - name: Sleep
        run: sleep 1h  # 将时间缩短为1小时，降低超时风险
